/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsNewRouteImport } from './routes/posts/new'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as AdminAgentsRouteImport } from './routes/admin/agents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsNewRoute = PostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/new': typeof PostsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/new': typeof PostsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/new': typeof PostsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/agents' | '/posts/$slug' | '/posts/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/agents' | '/posts/$slug' | '/posts/new'
  id: '__root__' | '/' | '/admin/agents' | '/posts/$slug' | '/posts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  PostsSlugRoute: typeof PostsSlugRoute
  PostsNewRoute: typeof PostsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/new': {
      id: '/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof PostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  PostsSlugRoute: PostsSlugRoute,
  PostsNewRoute: PostsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
